# Generated by Django 3.2.13 on 2022-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_content_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
